"""Added description and status columns

Revision ID: a234d90ee2b7
Revises:
Create Date: 2025-09-13 21:18:15.323999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a234d90ee2b7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "todos",
        sa.Column("status", sa.String(), nullable=False, server_default="In Progress"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "status")
    op.drop_column("todos", "description")
    # ### end Alembic commands ###
